### ISSUE TITLE
Unauthorize Operation

### ISSUE THREAD

**Issue by matheus-meneses** [sercand/kuberesolver#24]
Hello Guys 

I'm facing the same issue in Aws EKS

EKS Data:

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

My Role
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mag-dev
  namespace: mag-dev
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
```

My Headless service
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: gubernator
  namespace: ratelimit
  labels:
    app: gubernator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc-port
      targetPort: 81
      protocol: TCP
      port: 81
    - name: http-port
      targetPort: 80
      protocol: TCP
      port: 80
  selector:
    app: gubernator
```

My grpc conn

```go
kuberesolver.RegisterInCluster()
resolver.Register(kuberesolver.NewBuilder(nil /*custom kubernetes client*/, "kubernetes"))
return grpc.Dial(address, grpc.WithBalancerName("round_robin"), grpc.WithInsecure())
```
address value : ```kubernetes:///gubernator.ratelimit:81```

Would you guys have any ideia what i'm doing wrong?

_Originally posted by @matheus-meneses in https://github.com/sercand/kuberesolver/issues/8#issuecomment-796796782_
