### ISSUE TITLE
Need more documentation about setup

### ISSUE THREAD

**Issue by luthfikw** [sercand/kuberesolver#8]
is need some configuration when running on kubernetes cluster
like RBAC or something like that?

this error messages:
`ERROR: 2019/10/29 03:34:29 kuberesolver: watching ended with error='invalid response code 403', will reconnect again`

**Comment by syllabix** [comment]
yep - you need GET and WATCH access to endpoints using a role

**Comment by luthfikw** [comment]
thank you that work!, can write it on the documentation or wiki later?

**Comment by kaskavalci** [comment]
I created the required resources on a GKE cluster ( version: 1.13.12-gke.25  ) on the namespace I deployed kuberesolver. However, I still experience the same problem. Aree there any further steps to be taken for GKE clusters?

**Comment by luthfikw** [comment]
sometimes i still got this message, but i don't know how to solve it

**Comment by kaskavalci** [comment]
In my case it is constant and client cannot make a connection to server. Basically, I couldn't make this work with GKE.

**Comment by syllabix** [comment]
@kaskavalci - have you set up your k8 service correctly? You will need to make sure its "headless" so the native k8 load balancer is disabled and `kuberesolver` can take over load balancing duties.
An example service definition:
```
apiVersion: v1
kind: Service
metadata:
  name: my-awesome-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: accounts

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 9092 // your pods are listening on 9092 
```

Then - you can 'dial' as follows (assuming your service is in the default namespace: 
```
grpc.Dial(
		kubernetes://default/my-awesome-service:8080,
		grpc.WithInsecure(), // not recommended but here for ease of setup in this example
		grpc.WithBalancerName(roundrobin.Name),
)
```

**Comment by sercand** [comment]
I have updated readme to include more information about usage

**Comment by matheus-meneses** [comment]
Hello Guys 

I'm facing the same issue in Aws EKS

EKS Data:

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

My Role
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mag-dev
  namespace: mag-dev
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
```

My Headless service
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: gubernator
  namespace: ratelimit
  labels:
    app: gubernator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc-port
      targetPort: 81
      protocol: TCP
      port: 81
    - name: http-port
      targetPort: 80
      protocol: TCP
      port: 80
  selector:
    app: gubernator
```

My grpc conn

```go
kuberesolver.RegisterInCluster()
resolver.Register(kuberesolver.NewBuilder(nil /*custom kubernetes client*/, "kubernetes"))
return grpc.Dial(address, grpc.WithBalancerName("round_robin"), grpc.WithInsecure())
```
address param is : ```kubernetes:///gubernator.ratelimit:81```

Would you guys have any ideia what i'm doing wrong?
